#define		SKIP_PREDICTION				0		// 0: OFF - 1: ON
#define		FAST_PU_DECISION			1		// 0: RDO FULL DECISION - 1: FAST PU DECISION
#define		FAST_CU_DECISION			0		// 0: RDO FULL DECISION - 1: FAST PU DECISION
#define		FAST_TU_DECISION			0		// 0: RDO FULL DECISION - 1: FAST PU DECISION

